apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-teste1
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-teste1
  template:
    metadata:
      labels:
        app: lab-teste1
    spec:
      containers:
      - name: lab-teste1
        image: leohurin/lab-teste1:a281c0373e4e54206062ed941920cf5847aa11ad
        ports:
        - containerPort: 80
