apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-teste1
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-teste1
  template:
    metadata:
      labels:
        app: lab-teste1
    spec:
      containers:
      - name: lab-teste1
        image: leohurin/lab-teste1:9993f6fb8826ad77630be2bd441bda24e256d7fb
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
