apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-teste1
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-teste1
  template:
    metadata:
      labels:
        app: lab-teste1
    spec:
      containers:
      - name: lab-teste1
        image: leohurin/lab-teste1:69bba96b3750c5a988047009b49c5d9b906c6a1b
        ports:
        - containerPort: 80
